apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- node-port.yaml
- deployment.yaml

images:
- name: kilaka/continuous-delivery-example:latest
  newName: kilaka/continuous-delivery-example
  newTag: 1.2.0
